### ISSUE TITLE
API Specification for SDK generation

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#1]
## Description
Design an OpenAPI based doc that can be used to generate a Go SDK using Autorest.

- Determine target version of OpenAPI for autorest
- Layout the API for command query separation
- Semantics for Authentication / Authorization
  - evaluate per call or set up a session start/end
- Include ability to schedule a deployment of an ARM template
- Event topics - get types, subscribe

**Comment by AnthonyByansi** [comment]
@kevinhillinger, can I take on this role "Design an OpenAPI based doc that can be used to generate a Go SDK using Autorest" ?

**Comment by kevinhillinger** [comment]
Thank you for the offer @AnthonyByansi but this was already assigned and completed.
