### ISSUE TITLE
DryRun Validator: KubernetesOperationError

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#24]
When deploying a kubernetes solution, there can be operation errors brought on by things like namespace conflicts, or misconfiguration.  

During the DryRun process, it would be great to have a validator be able to catch issues like this prior to deployment.

Proposal: Create a validator that will run when there are existing AKS instances that will delegate a dry-run call to the kubernetes cluster, and report results.

**Comment by kevinhillinger** [comment]
We will NOT be validating kubernetes at this time. we may revisit
