### ISSUE TITLE
Enhancement: Wire up event hook subscription as part of CreateDeployment

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#244]
Currently, there is a separate api call for subscribing to event hooks.  This could potentially lead to someone calling startdeployment/dryrun without ever getting notifications back because they never previously called createeventhook.

Adding an implicit eventhook registration could avoid this situation.

**Comment by kevinhillinger** [comment]
Adding thoughts here: we may not want to do this, since we currently only support a hook registration for all events, rather than a specific event type(s).
