### ISSUE TITLE
Github Workflow - build

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#27]
- Build workflow
- Builds `cmd/apiserver` and `cmd/operator`
- Runs all tests
- Use Makefile and implement targets where needed to facilitate this.
- Consolidate .json config files to .env

**Comment by kevinhillinger** [comment]
We need to run integration tests live against our central azure sub.

**Comment by kevinmgates** [comment]
Added [.github/workflows/ci.yml ](https://github.com/microsoft/commercial-marketplace-offer-deploy/blob/main/.github/workflows/ci.yml)
- make targets to build apiserver, operator
- make target to call go test at the project root
- gets config secrets and populates .config file
- logs into azure using SP
- runs all tests
