### ISSUE TITLE
Dry run started and completed events received multiple times w/ same info

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#301]
Duplications in events for dry run start/complete..

`time="2023-06-06 23:15:49" level=debug msg="RAW event: dryRunScheduled - /deployments/1 - map[attempts:0 completedAt:2023-06-06T23:15:47.058551993Z deploymentId:1 operationId:e728372c-d460-44e7-b75f-a8505d4c43ad startedAt:2023-06-06T23:15:47.058551993Z status:error]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-06 23:15:49" level=debug msg="RAW event: dryRunStarted - /deployments/1 - map[attempts:1 completedAt:2023-06-06T23:15:47.597487523Z deploymentId:1 operationId:e728372c-d460-44e7-b75f-a8505d4c43ad startedAt:2023-06-06T23:15:47.058551993Z status:error]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-06 23:15:50" level=debug msg="RAW event: dryRunStarted - /deployments/1 - map[attempts:1 completedAt:2023-06-06T23:15:47.597487523Z deploymentId:1 operationId:e728372c-d460-44e7-b75f-a8505d4c43ad startedAt:2023-06-06T23:15:47.058551993Z status:error]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-06 23:16:07" level=debug msg="RAW event: dryRunCompleted - /deployments/1 - map[attempts:1 completedAt:2023-06-06T23:15:47.597487523Z deploymentId:1 operationId:e728372c-d460-44e7-b75f-a8505d4c43ad startedAt:2023-06-06T23:15:47.058551993Z status:success]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-06 23:16:07" level=debug msg="RAW event: dryRunCompleted - /deployments/1 - map[attempts:1 completedAt:2023-06-06T23:15:47.597487523Z deploymentId:1 operationId:e728372c-d460-44e7-b75f-a8505d4c43ad startedAt:2023-06-06T23:15:47.058551993Z status:success]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"`

[log-SandboxHost-638216900159145425.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11671086/log-SandboxHost-638216900159145425.operator.txt)
[log-SandboxHost-638216900159145425.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11671087/log-SandboxHost-638216900159145425.apiserver.txt)
[modm.db.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11671090/modm.db.txt)

**Comment by bobjac** [comment]
Thanks @bhavenst.  We'll triage and get assigned.

**Comment by kevinhillinger** [comment]
resolved in v1.3.1
