### ISSUE TITLE
Request to provide events for stage start and stage complete

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#302]
In order for us to show progress on the UI, we need a way of getting status (start/stop/result) for each stage.  This is also needed for restarting stages when they fail.  Please add events for these.

(this is already planned, just creating an issue to track)

**Comment by kevinhillinger** [comment]
@bhavenst - this is going to be resolved in next v1 publish. The event types that will come through:

stageStarted
StageCompleted

**Comment by kevinhillinger** [comment]
Regression bug

**Comment by kevinhillinger** [comment]
fixed
