### ISSUE TITLE
MODM deploys over and over and ...

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#303]
I've seen this in both of the last 2 runs with 1.3.0.  The deployment completes successfully, but then starts again, completes again, starts again, etc.

These are the events received before the deployment driver eventually timed out and stopped printing them (though modm still running and deploying).

`time="2023-06-07 16:08:16" level=debug msg="RAW event: deploymentScheduled - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 16:08:17" level=debug msg="RAW event: deploymentStarted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:16:00" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:16:01" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:29:39" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:29:40" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:41:48" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:41:49" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:53:56" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 17:53:58" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 18:06:05" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-07 18:06:06" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"`

[modm.10.db.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11680785/modm.10.db.txt)

[log-SandboxHost-638217506390554897.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11680782/log-SandboxHost-638217506390554897.operator.txt)
[log-SandboxHost-638217506390554897.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11680784/log-SandboxHost-638217506390554897.apiserver.txt)

**Comment by kevinhillinger** [comment]
Regression, being fixed by @bobjac

**Comment by kevinhillinger** [comment]
fixed
