### ISSUE TITLE
SDK does not define dryRunStarted event

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#310]
dryRunStarted events are received, but just doing string comparison. SDK is missing (at least) that event type:

`const (
	EventTypeDeploymentCreated   EventTypeName = "deploymentCreated"
	EventTypeDeploymentUpdated   EventTypeName = "deploymentUpdated"
	EventTypeDeploymentDeleted   EventTypeName = "deploymentDeleted"
	EventTypeDeploymentScheduled EventTypeName = "deploymentScheduled"
	EventTypeDeploymentStarted   EventTypeName = "deploymentStarted"
	EventTypeDeploymentCompleted EventTypeName = "deploymentCompleted"
	EventTypeStageCompleted      EventTypeName = "stageCompleted"
	EventTypeStageRetried        EventTypeName = "stageRetried"
	EventTypeStageStarted        EventTypeName = "stageStarted"
	EventTypeStageScheduled      EventTypeName = "stageScheduled"
	EventTypeDeploymentRetried   EventTypeName = "deploymentRetried"
	EventTypeDryRunCompleted     EventTypeName = "dryRunCompleted"

	EventTypeDeploymentOperationReceived EventTypeName = "deploymentOperationReceived"
	EventTypeDeploymentEventReceived     EventTypeName = "deploymentEventReceived"
)`

**Comment by kevinhillinger** [comment]
Affected version: v1.3.1

**Comment by kevinhillinger** [comment]
resolved
