### ISSUE TITLE
Bug: EventHookMessage - startedAt timestamp unchanged 

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#312]

**Comment by bhavenst** [comment]
I'm more worried about completedAt.  startedAt (might) be fine as is.

**Comment by kevinhillinger** [comment]
Agreed. StartedAt doesn't make sense. We will NOT be including that where it isn't relevant along with making sure the correct timestamp value is set

**Comment by bhavenst** [comment]
Just to be clear, I would be fine if the started and scheduled messages drop the startedAt and completedAt entirely, but would like to have those present in the completed message so that we can show execution time.

**Comment by kevinhillinger** [comment]
resolved
