### ISSUE TITLE
Stage messages not coming as expected (v1.3.1)

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#313]
In the run I showed during the teleconf, I noticed there was only one StageStarted message and no completed or additional stage started.  However, the deployment is far along and many stages have started and completed.  See screenshot from Azure.

All deployment related events received:

`time="2023-06-08 18:35:27" level=debug msg="RAW event: deploymentScheduled - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:27" level=debug msg="RAW event: deploymentStarted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:38" level=debug msg="RAW event: stageStarted -  - map[attempts:1 completedAt:0001-01-01T00:00:00Z correlationId:79be8380-b4a9-4c47-a6d5-74f786ca1cb8 deploymentId:1 operationId:bd9b53ec-79d6-4b7d-af57-872e66e45fd2 stageId:f62ab2b3-234f-48a5-b859-3e7a5a677b3b startedAt:2023-06-08T18:35:28.829276524Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"`

At this point there should be 5 stages started and completed and one more started.

![image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/49794041/b1e12599-78a3-4c69-bcc2-a20bb70df55e)
[log-SandboxHost-638218459197532688.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11692162/log-SandboxHost-638218459197532688.operator.txt)
[log-SandboxHost-638218459197532688.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11692163/log-SandboxHost-638218459197532688.apiserver.txt)
[modm.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11692165/modm.zip)

**Comment by kevinhillinger** [comment]
Investigating now

**Comment by bhavenst** [comment]
Full set of messages for this dry run + deployment:

`time="2023-06-08 18:35:07" level=debug msg="RAW event: dryRunScheduled - /deployments/1 - map[attempts:0 completedAt:2023-06-08T18:35:04.310234194Z deploymentId:1 operationId:0fea983d-d75f-4446-a5c6-8a24ba878974 startedAt:2023-06-08T18:35:04.310234194Z status:error]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:07" level=debug msg="RAW event: dryRunStarted - /deployments/1 - map[attempts:1 completedAt:2023-06-08T18:35:05.42470714Z deploymentId:1 operationId:0fea983d-d75f-4446-a5c6-8a24ba878974 startedAt:2023-06-08T18:35:04.310234194Z status:error]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:24" level=debug msg="RAW event: dryRunCompleted - /deployments/1 - map[attempts:1 completedAt:2023-06-08T18:35:05.42470714Z deploymentId:1 operationId:0fea983d-d75f-4446-a5c6-8a24ba878974 startedAt:2023-06-08T18:35:04.310234194Z status:success]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:27" level=debug msg="RAW event: deploymentScheduled - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:27" level=debug msg="RAW event: deploymentStarted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 18:35:38" level=debug msg="RAW event: stageStarted -  - map[attempts:1 completedAt:0001-01-01T00:00:00Z correlationId:79be8380-b4a9-4c47-a6d5-74f786ca1cb8 deploymentId:1 operationId:bd9b53ec-79d6-4b7d-af57-872e66e45fd2 stageId:f62ab2b3-234f-48a5-b859-3e7a5a677b3b startedAt:2023-06-08T18:35:28.829276524Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"
time="2023-06-08 19:40:16" level=debug msg="RAW event: deploymentCompleted - /deployments/1 - <nil>" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"`

**Comment by kevinhillinger** [comment]
Related to #309 where message deduplication wasn't hashing correctly. Resolved.
