### ISSUE TITLE
Message / Service Bus - reliable capture of Azure events

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#32]
Deployment Management needs a reliable message bus that can reliably persist messages across runtime failures if the service goes down and starts back up.

The purpose of this messaging bus is to capture all events from Azure and any internal events and send them to a central queue for all messages. 

The message placed on this "events queue" will have a standard format that identifies the "topic" of the message's event.

These "event messages" are then dequeued and a POST occurs to any subscriptions (via web hook from the SDK). If there aren't any subscriptions the message is logged by default and then discarded.

**Comment by bobjac** [comment]
I'll take it
