### ISSUE TITLE
Stage messages not received as desired v1.3.2

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#330]
Still only getting a single stageStarted and no stageCompleted.

`time="2023-06-09 19:56:02" level=debug msg="RAW event: type: dryRunScheduled - subject: /deployments/1 - status: scheduled - data: map[attempts:0 deploymentId:1 operationId:328c4403-4900-4a78-9acf-f293f5af098e scheduledAt:2023-06-09T19:55:59.324838056Z status:scheduled]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 19:56:05" level=debug msg="RAW event: type: dryRunStarted - subject: /deployments/1 - status: running - data: map[attempts:1 deploymentId:1 operationId:328c4403-4900-4a78-9acf-f293f5af098e startedAt:2023-06-09T19:56:02.722687304Z status:running]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 19:56:21" level=debug msg="RAW event: type: dryRunCompleted - subject: /deployments/1 - status: success - data: map[attempts:1 completedAt:2023-06-09T19:56:21.305314924Z deploymentId:1 operationId:328c4403-4900-4a78-9acf-f293f5af098e startedAt:2023-06-09T19:56:02.722687304Z status:success]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 19:56:31" level=debug msg="RAW event: type: deploymentScheduled - subject: /deployments/1 - status: scheduled - data: map[attempts:0 deploymentId:1 operationId:92d14a44-8de1-4a45-b758-c71de3220f95 scheduledAt:2023-06-09T19:56:30.78902544Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 19:56:32" level=debug msg="RAW event: type: deploymentStarted - subject: /deployments/1 - status: running - data: map[attempts:1 deploymentId:1 message:deploy started operationId:92d14a44-8de1-4a45-b758-c71de3220f95 startedAt:2023-06-09T19:56:31.778817971Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 19:57:04" level=debug msg="RAW event: type: stageStarted - subject: /deployments/1/stages/2e1c8b57-7045-4b53-93c0-4d2e24a99834 - status: running - data: map[attempts:1 correlationId:b3846334-edd2-4148-ac05-60cf53f8bda6 deploymentId:1 operationId:92d14a44-8de1-4a45-b758-c71de3220f95 stageId:2e1c8b57-7045-4b53-93c0-4d2e24a99834 startedAt:2023-06-09T19:56:33.320516378Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-09 21:14:52" level=debug msg="RAW event: type: deploymentCompleted - subject: /deployments/1 - status: success - data: map[attempts:1 completedAt:2023-06-09T21:14:45.773972348Z deploymentId:1 operationId:92d14a44-8de1-4a45-b758-c71de3220f95 startedAt:2023-06-09T19:56:31.778817971Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"`

[log-SandboxHost-638219372314243813.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11710177/log-SandboxHost-638219372314243813.apiserver.txt)
[log-SandboxHost-638219372314243813.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11710178/log-SandboxHost-638219372314243813.operator.txt)

[modm.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11710181/modm.zip)

**Comment by bhavenst** [comment]
v1.3.2

**Comment by kevinhillinger** [comment]
investigating
