### ISSUE TITLE
Never received stageCompleted for a completed stage

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#339]
Ran a full deployment and got everything except one stageCompleted.  So the UI was left with one spinning icon even though it was all complete. :)  Attaching logs and db.

`
[bhavenst@fedora Downloads]$ grep fbecfd48-cc98-4bbd-a79f-e6503d2b352d engine\ \(3\).txt

time="2023-06-12 23:38:19" level=debug msg="RAW event: type: stageScheduled - subject: /deployments/1/stages/fbecfd48-cc98-4bbd-a79f-e6503d2b352d - status: scheduled - data: map[attempts:0 deploymentId:1 operationId:89bbd46d-f133-4972-bc6a-950177cb2472 parentOperationId:1c30a069-5029-4a32-a285-a9b3894569b0 scheduledAt:2023-06-12T23:38:13.081121339Z stageId:fbecfd48-cc98-4bbd-a79f-e6503d2b352d]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-12 23:38:23" level=debug msg="RAW event: type: stageStarted - subject: /deployments/1/stages/fbecfd48-cc98-4bbd-a79f-e6503d2b352d - status: running - data: map[attempts:1 deploymentId:1 operationId:89bbd46d-f133-4972-bc6a-950177cb2472 parentOperationId:1c30a069-5029-4a32-a285-a9b3894569b0 stageId:fbecfd48-cc98-4bbd-a79f-e6503d2b352d startedAt:2023-06-12T23:38:21.330016195Z]" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:29"

time="2023-06-12 23:38:23" level=debug msg="Received event: Stage started: /deployments/1/stages/fbecfd48-cc98-4bbd-a79f-e6503d2b352d" func=server/handler.EventHook file="/home/bhavenst/repos/azure-aap-deployment-driver/server/handler/eventhook.go:40"
`

[log-SandboxHost-638222097034401694.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11729490/log-SandboxHost-638222097034401694.operator.txt)
[log-SandboxHost-638222097034401694.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11729491/log-SandboxHost-638222097034401694.apiserver.txt)

[modm.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11729501/modm.zip)

**Comment by kevinhillinger** [comment]
Can you please call `az deployments group list` to view the state of the seeded content?

**Comment by kevinhillinger** [comment]
@bhavenst, let us know if this is resolved. we've confirmed in our unit and scenario tests that this is resolved.

For failed or success status, this event message will still get sent, but MODM will not send it until ALL retries have been performed and received a signal of a final success or failure from Azure.

**Comment by bhavenst** [comment]
Hi @kevinhillinger as I posted on the channel yesterday, we are still seeing this along with unwarranted failures.  All the files are on the channel..

**Comment by kevinhillinger** [comment]
@bhavenst we've reviewed the logs, and all operations succeeded. There was 1 retry on the "AAP__Applications" Stage, however, that succeeded as well. 

What we see is a failure in your driver to continue to receive HTTP connections over port 9090, which is represented in the logs in both cases. This will cause all event messages to be received. In all our setup, we've never logged HTTP communication failures. 

If infrastructure integration setup isn't correct for multi-container, and state is updated based on messages, and messages can no longer be delivered, the driver's state will not accurately reflect.

We audit all event messages that are attempted. All stageCompleted event messages were captured, but couldn't be delivered. Here's an example event message that was audited:

```
{
    "id": "a1a2c528-e27f-4acf-b699-68ce434f0ece",
    "hookId": "d3dcb35d-698b-45b5-9f98-7638bf7636ca",
    "type": "stageCompleted",
    "status": "success",
    "subject": "/deployments/1/stages/ab937ffc-57e1-43ed-8f3a-1402a9fba426",
    "data": {
        "attempts": 1,
        "completedAt": "2023-06-15T22:57:58.546630151Z",
        "deploymentId": 1,
        "operationId": "568f36cd-73c0-4c9b-b2a6-1f8d49a5dfbf",
        "parentOperationId": "5764285d-fa01-469e-9cce-6102bda82daf",
        "stageId": "ab937ffc-57e1-43ed-8f3a-1402a9fba426",
        "startedAt": "2023-06-15T22:52:17.48150082Z"
    }
}
```

**Comment by bhavenst** [comment]
Hi Kevin, this just doesn't match my experience.  I think there is an explanation (below) for the missed events..  But there are multiple failures and errors being sent that are indeed received.  Definitely doesn't look like one step retried once and all the rest were fine.  I have just deployed another one and here are the received events as well as the files for examination.  In this case, it was the same in that one stage did legitimately fail once and was successful on retry and all the others succeeded (AAP__Operators 1429365b-b8fb-4943-b57d-93e4d10dcc1a is the one that failed).  But in this case we got 3 stageCompleted with failure state.

![image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/49794041/7ed77f35-8100-4044-aa3f-c61be77065fd)


There was also this strange set of events that seem half baked (just an aside):

time="2023-06-19 17:45:53" level=debug msg="RAW event: type: Scheduled - subject: /deployments/1 - status: scheduled - data: <nil>" func=server/handler.EventHook file="eventhook.go:29"
time="2023-06-19 17:45:57" level=debug msg="RAW event: type: Pending - subject: /deployments/1 - status: pending - data: <nil>" func=server/handler.EventHook file="eventhook.go:29"
time="2023-06-19 17:46:03" level=debug msg="RAW event: type: Completed - subject: /deployments/1 - status: success - data: <nil>" func=server/handler.EventHook file="eventhook.go:29"


AAP__Operators failed as mentioned

Since I was watching, I noticed that upon the stage failure, MODM retried the entire deployment starting with stage 1.  The deployment driver just re-executes the failed stage and then continues, so this is a difference w/ deployment driver.  After that, while most of the deployments were replaced but some still in progress, modm restarted the whole deployment again from the start.  I don't think I missed any failure there, so it seems like that was spurious.  And the fact that it restarted the deployment while the other one was still in progress is strange.  To be specific, AAP__Operators (the rerun) was still in progress w/ about 8 minutes having elapsed.  But then VNETS__and__Subnets, AAP__Repository, Private__DNS etc. ran again while that one was still running from before.  So then I was still watching and when AAP__Operators did finish (successfully)...  It restarted the entire deployment again!  This does not seem like proper behavior and even if somehow explainable, a lot of time is wasted redeploying things that are already successfully deployed.  Some items take 1 second, but a lot of them take a lot longer even though they're idempotent..

After watching all this, I think the missed events are caused because the deployment driver goes into a waiting mode when a stage fails and waits 30 min for the user to restart the stage and then 15 more (nothing can be restarted then, just some time to look at the UI etc. before it shuts down).

In my opinion, no stageCompleted with fail should ever be received until the internal retries have been exhausted.  Because that is the state at which we want to present to the user the option to retry (another set of internal retries).

In this run there were 3 stageCompleted with failure state, but the errors are related to something like MODM attempting to re-execute rather than anything to do with any actual failure.  Not to mention that they are for 3 different steps, 2 of which never failed at all.  They just say "Error: unable to redeploy the deployment".

I can't really see what happens as far as messaging after this point since the deployment driver has died.  But I did watch the remainder of the deployment via azure UI and it looked OK, just 1 pass through the remaining steps.

By the way, in the logs you'll see another deployment #2 at the end.  That can be ignored because I tried restarting the deployment driver then and it tried to redeploy rather than realizing everything was done.

[modm.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11791306/modm.zip)

[log-SandboxHost-638227912063904333.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11791307/log-SandboxHost-638227912063904333.apiserver.txt)

[operator-log.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11791301/operator-log.zip)

**Comment by bhavenst** [comment]
Another view of the received messages for this run.
![image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/49794041/784219f7-09ae-4130-8f86-fac292fefc68)

**Comment by bobjac** [comment]
@bhavenst - I am taking a look this afternoon.  I'll let you know what I find.

**Comment by bhavenst** [comment]
Today I did another deployment with all the retry values set to 0.  In this deployment, nothing failed.  From the deployment driver perspective it pretty much worked as advertised.

The issues I can see are that there was a deployment retry captured and I have no idea why that would have occurred.  It is visible from the received events.

Also I noticed after the last deployment was complete in the Azure UI (and the modm parent deployment complete) it was a few minutes later that the second to last stageComplete came and then 4 minutes later I got TWO deploymentComplete events.  Then a bit later the last stageComplete came.

So everything was received and the deployment driver exited properly, just noticed that retry anomaly and the doubled deploymentComplete messages.

So it seems like most of it works OK in the happy case when everything passes but the failure handling has more issues and discrepancies..

Other than the ordering issue, the UI is happy.

![image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/49794041/422fdf22-de78-4ad9-93ad-42faf97f8a09)


[modm.db.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807600/modm.db.zip)
[operator.log.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807601/operator.log.zip)
[log-SandboxHost-638228881956093847.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807603/log-SandboxHost-638228881956093847.apiserver.txt)

**Comment by bobjac** [comment]
I am looking into the retry issues.  I am OOF today and tomorrow, but there seems to have been some throttling in the subscription from the Azure side when checking for the current state.  So the deployment was executing fine, the status check resulted in a throttle which would be considered a failure, and would trigger a retry.

**Comment by bhavenst** [comment]
Thanks for the update.  I assume that will be handled not as a failure, but just retried without any notification to the client..

**Comment by kevinhillinger** [comment]
The stageCompleted is being received but not in the frequency desired. Creating #355 to track
