### ISSUE TITLE
MODM refuses to die

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#347]
I decided to test deployment cancellation since I have not done that in a clean way before.

So started a deployment as usual.

After a couple of steps were complete, hit the cancel button, which calls client.Cancel(context, depId).

1. MODM parent deployment cancelled as shown in Azure UI (child deployments not cancelled but remain running, so that may or may not be a problem)
2. MODM restarts the deployment!  (definitely a problem).  After a bit this one shows cancelled as well.
3. MODM restarts the deployment! (definitely a problem).  This one is still running, just going on to deploy the whole thing.

See attached files.
[modm.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807910/modm.zip)
[log-SandboxHost-638228941213527415.operator.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807911/log-SandboxHost-638228941213527415.operator.txt)
[log-SandboxHost-638228941213527415.apiserver.txt](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/11807914/log-SandboxHost-638228941213527415.apiserver.txt)

**Comment by kevinhillinger** [comment]
Tracking via #354
