### ISSUE TITLE
MODM does not stop when a step/stage fails and re-executes entire deployment

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#348]
We have the retry field set to 3 for each step.

MODM should:

1) send stageStarted
2) <stage execution 0, fails>
3) <retry 1, fails again>
4) <retry 2, fails again>
5) <retry 3, fails again>
6) send stageCompleted with status failure, 4 error blocks attached
6a) continue any independent parallel stages to completion
7) stop deploying
8) wait for a stage restart to come in (or a cancel)
9) <stage restart received>
10) send stageStarted
10) <stage execution 4, fails>
11) <retry execution 5, fails again>
12) <retry execution 6, fails again>
13) <retry execution 7, fails again>
14) send stageCompleted with status failure, 4 error blocks attached

etc.

The problems that have been observed in reference to this are:

- Stages are not retried, the entire deployment is retried
- stageCompleted events are received even for "internal" retries, which is confusing
- MODM does not stop when a stage fails, though maybe it would if it reached the max retries (which is fine if that is the case)

For our controller to understand what is happening, we need to treat each set of initial run + "internal" retries as an atomic unit that have one start and complete.

**Comment by kevinhillinger** [comment]
v2 implementation reworked to no longer include "stages" as a concept as they are brittle and create unnecessary complexity and overhead.
