### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by bhavenst** [microsoft/commercial-marketplace-offer-deploy#350]
We are unable to make much sense of the logs currently for operator and api server.

In another issue I mentioned that there were 247 stageCompleted messages sent.  This was just a grep of the operator log.  However in looking into that there are many repetitions with slight differences of these messages, so it is impossible to tell how many were sent and at what time.

Probably debugging has been added and added to help track down issues, but the logs are overly verbose and confusing at this point.

We will need for SREs to be able to look at the logs and understand what is happening when MODM is in production so paring down to a good level for understanding what has gone wrong without overwhelming them is necessary.

I have been working with MODM for weeks now and I find it very hard to figure out what is happening from the logs myself.  Part of that is the distributed and asynchronous nature of MODM, but hopefully the situation can be improved.

**Comment by kevinhillinger** [comment]
@bhavenst thank you for raising this up as an issue. 

Issue #351 focuses on observability for logging to address this.
