### ISSUE TITLE
spike: VM Gallery image + service catalog offer

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#360]
## Summary
Have a local service catalog that contains an azure resource that contains an instance of a Virtual Machine image deployed to an image gallery that exists in an Azure subscription.  The intent is to simulate creating a marketplace VM image that will do installations of complex marketplace solutions using currently unsupported deployment types (terraform, scripts, etc).

## Notes

The setup for a Service catalog that makes use of a virtual machine image can be automated.  There are 2 key parts that can be executed independently or a coordination script can be added.  The two key parts are:
- Build the image and deploy to gallery
- Create the service catalog that references the image in the gallery

For the first part of building the image and deploying to the gallery, you can setup all needed service principals and permissions using the /src/BaseVMImage/packer/setup.sh script.  The setup.sh script needs to be executed only once.  You can then build the virtual machine image using packer by calling /src/BaseVMImage/packer/buildImage.sh.

The second part is building the service catalog managed application that references the created image.  This is also broken into 2 scripts that can be coordinated.  The first script to execute is /src/BaseVMImage/createAppZip.sh. This zips up the mainTemplate.json file along with the createUiDefinition and stores it in the local directory.  The second script to run is the /src/BaseVMImage/createServiceDefinition.sh file.  This will automate the process of:
- creating a storage account if it doesn't exist in the passed in resource group
- creates a storage account container 
- upload the app.zip to the container
- grant appropriate permissions to the azure security group
- creates a unique resource group for the managed app definition
- creates that managed app definition in the created resource group

## Unresolved

There are a couple areas of improvement that need to be resolved
- currently, the security group that is being used for permissions assigned to the managed application definition is setup by hand and should be automated.  The group name is bobjacmarketplace and is referenced in /src/BaseVMImage/createServiceDefinition.sh, but I will parameterize that once I have the automated script it place.
- The buildImage.sh script builds the correct VM image.  This image is referenced in the mainTemplate.json file.  There is no automated script in place right now to move it into an image gallery.  I am adding that script this week and will adjust the mainTemplate.json file accordingly.  I have tested and verified that the image gallery works manually.
- I plan on adding a root coordination script that will delegate to these individual scripts to make setup as easy as possible.  I will add this once all the individual pieces are in place.

**Comment by bobjac** [comment]
The automation of integrating with the gallery is complete.  To full automate, we will need to modify the mainTemplate content with the image's gallery reference and set the proper permissions.  This is next step.
