### ISSUE TITLE
Auto delete MODM from Azure

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#490]
# Requirement
MODM resource such as the virtual machine, vnet, nic, etc, are only installed to the managed resource group in order to support the modm installer.  These resources be tagged to serve a cleanup process that is either triggered by the user or on a timer after the install.

## Success Criteria 
- All deployed resources used to support the modm installer should have a "modm" tag applied to it.
- Auto-deletes in 6 hours from time of startup 

## Justification
We should not be adding orphaned resources to to customer's tenant.  Resources that we create for our purposes need to be identified so we can filter or remove.

# Implementation
The most straightforward way to do it is by added the modm tag directly to the resources in the mainTemplate.json.  This should be done for all of out test scenarios as well as the mainTemplate.json that will be used by the cli.
 
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/commercial-marketplace-offer-deploy/issues/518
```

**Comment by kevinhillinger** [comment]
Done. Closing
