### ISSUE TITLE
ui: create live success/failure component

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#499]
# Requirement

The user interface needs to present the total successful and failed resources that are being installed.  This card is a quick visual indicator into the state of the deployment.  This will be expanded to act as a filtering mechanism in a future issue.

## Success Criteria 

- A single visual card that is a shade of red that shows the total number of resources that failed deployment
- A single visual card that is a shade of green that shows the total number of resources that successful deployment

## Justification

When deploying a marketplace solution, the user will want to see the current status of their deployed resources.  Visual cards will help the user quickly understand the state of the deployment and enable filtering capabilities that will greatly aid in determining if there are any parameters that need to be modified in for a redeployment.

# Implementation
- Create a react component that has 2 visual cards using the fluent ui
- Add a javascript map to filter and aggregate the total number of successes and failures

**Comment by Alone-Y154** [comment]
Hi @bobjac & @kevinhillinger, I would like to work on this issue, can you assign it to me
