### ISSUE TITLE
ui: add icon next to name based on resource type (installed resources)

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#500]
# Requirement
Currently, the Installation table is a simple table that shows the installed resources.  This table should have a similar feel to the Azure portal and display the resource icon next to the name.

## Success Criteria 

Currently, the installation table looks like the following:

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/ba48b95c-2a7a-4abc-a739-ed2fcba82e10)

It should look like:

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/b50e2c3a-75cd-41a7-b685-d41774cf8be2)

## Justification

We want the experience to feel as native as possible to the Azure Portal

# Implementation

The react component should be updated to include the appropriate icons.

**Comment by kevinhillinger** [comment]
Agreed. This is a nice to have and doesn't add value.
