### ISSUE TITLE
investigate: Seamlessly tie installed managed app output to dashboard

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#501]
# Requirement

A user that is installing a marketplace solution via modm needs to know the fully qualified domain name of the virtual machine so they can access the ui/dashboard.  Right now, there is no way to embed dynamic content into the managed application's view in the portal.  This requirement covers identifying the practice for doing that.

## Success Criteria 

- A user is able to either find where the url to the dashboard is from the managed app view, or is able to launch it directly from a link.

## Justification

A user needs to be able to reach the dashboard and know where to go.

# Implementation

? - A technical spike is open, but implementation details are not solidified yet.

**Comment by kevinhillinger** [comment]
This was implemented through the app service and app configuration. Duplicate.
