### ISSUE TITLE
ui: create live logged in user component

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#502]
# Requirement
Currently, the user icon in the UI just shows a sample user.  This needs to be updated with a live user.

## Success Criteria 

Currently, the logged in user looks like:

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/c6290777-f261-4107-8025-6a5e3d0145bc)

It should show the actual logged in user.

## Justification

The dashboard/site needs to authenticate the user through Azure AD.

# Implementation

The react component should work with msal to user the user is logged in and authenticated.  The component should pull the data of the logged in user for display.

**Comment by kevinhillinger** [comment]
No longer needed due to change of direction to use basic username/password auth.
