### ISSUE TITLE
deploy: Support for ARM deployments

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#504]
# Requirement
MODM needs to support native Azure Resource Manager deployments.  It is probably that Azure Resource Manager templates will be the most commonly deployed templates.  MODM requires complex ARM temples can be deployed.

## Success Criteria 
- Azure Resource Manager temples that meet the Azure Marketplace requirements are able to be deployed

## Justification
ARM templates are the standard way of deploying marketplace solutions so it must be supported

# Implementation
- Create a jenks job that mirrors the terraform job
  - Add init-hook with a hudson.tasks.Shell builder
  - deploy.sh will call the `az group deployment create` commend to install the mainTemplate and supporting template in the content.zip file

**Comment by kevinhillinger** [comment]
This is extremely low. Revisit based on partner needs in the future

**Comment by bobjac** [comment]
Bicep support complete.
