### ISSUE TITLE
Deployment status ui - component

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#515]
# Requirement

The MODM installer needs a component to indicate if status of the running deployment.  This should feel like an extension to the Azure Portal and display one of the following 3 states:

1.  "In Progress"

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/69898d40-7756-4642-bf60-854a71f93b1b)

2. "Complete" (Success)

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/774d3b20-de15-490a-a5e9-444092967f28)

3. "Failed"

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/7d7e8efc-bafb-4160-8599-1a0eccdd9227)

## Modifications

Instead of **Deployment Name**, we will replace with **Deployment Id** since our API is using that as a key.  This will allow us to support engines like Terraform that don't have specific deployment names.

**Correlation Id** will not be included as it doesn't have a strong counterpart in Terraform.
 
# Business Justifications

We want this to feel like an extension to the Azure Portal

# Implementation

- React component will use the output of the Deployment object from the api call to build the visual show in the requirement

**Comment by kevinhillinger** [comment]
Completed in cycle 1
