### ISSUE TITLE
Resource Status

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#516]
# Requirement

The UI state component should display the state of a deployment in the same view as the Azure portal.  It should take on the following form:

![Image](https://github.com/microsoft/commercial-marketplace-offer-deploy/assets/1582053/4c38f84b-4006-4e8b-a9f9-baadd647974e)

# Business Justification

The goal of the installer is to make it feel like an extension of the Azure portal UI

# Implementation
- Develop react component that that data Properties view model that deflects the table columns

**Comment by kevinhillinger** [comment]
Completed in cycle 1
