### ISSUE TITLE
When deploying a managed application results in an error: The language expression property 'location' doesn't exist

### ISSUE THREAD

**Issue by dparv** [microsoft/commercial-marketplace-offer-deploy#661]
Full error is:
```
{
    "status": "Failed",
    "error": {
        "code": "ApplicationProvisioningFailed",
        "message": "Deployment template validation failed: 'The template variable 'location' is not valid: The language expression property 'location' doesn't exist, available properties are 'name, properties'.. Please see https://aka.ms/arm-functions for usage details.'.",
        "additionalInfo": [
            {
                "type": "TemplateViolation"
            }
        ]
    }
}
```

Attaching the app.zip

[app.zip](https://github.com/microsoft/commercial-marketplace-offer-deploy/files/14948824/app.zip)

**Comment by bobjac** [comment]
What I did was set the output of the createUiDefinition to be:

"outputs": {
           "location": "[location()]",
...

That will set it to the managed resource group, not the resource group that contains the managed application.  Then in my mainTemplate, I did this:

...
param location string
...
module networkBaseDeployment 'modules/networkBaseDeployment.bicep' = {
 name: 'networkBaseDeployment'
 scope: az.resourceGroup(resourceGroupName)
 params: {
   location: location
///

That will flow the managed resource group to the resource.

**Comment by bobjac** [comment]
This is resolved.  This was an issue with the Bicep template.
