### ISSUE TITLE
Pull and Serialize Linked/Nested Deployments from Arm Template

### ISSUE THREAD

**Issue by bobjac** [microsoft/commercial-marketplace-offer-deploy#68]
When a deployment is kicked off, there will need to be notifications sent back to registered webhooks with deployment events.  To ensure proper event notification hierarchy, the system will need to pull top level deployment objects and build a serialize it so that it can be used in a real-time lookup.

**Comment by kevinhillinger** [comment]
This is solved now through resource tagging, using `modm.events = true` and implemented in `/cmd/operator/eventgrid/eventsfiltering`
