### ISSUE TITLE
Logging - logs, events, tracing [Starter]

### ISSUE THREAD

**Issue by kevinhillinger** [microsoft/commercial-marketplace-offer-deploy#72]
We need app telemetry. Implement a logger with application insights so we can send all

Location of code: `./internal/log` so that we can it like:

```go
import (
'internal/log'
)

...
log.Print()
log.Printf()
```

## Starting Implementation
- `logger.go`
- interface for the logger. (investigate standard logging interface for Go)
- pull in the correct SDK for Application Insights
- Implement Print() and confirm log is sent to app insights instance
- add a test `logger_test.go` and create 1 test for Print() that writes to application insights

### Environment configuration
- add to /configs/.env example the following Key: APPLICATION_INSIGHTS_INSTRUMENTATION_KEY

**Comment by kevinmgates** [comment]
Log levels (debug, etc)
Needs to send to stdout and app insights
https://github.com/uber-go/zap

**Comment by kevinhillinger** [comment]
- Logging now working as async to App Insights
- sample of logsrus and app insights

## TODO:
- wrapper "package" for /internal/log for all standard logging functions
- internal wrapper writes to standard out + app insights

**Comment by kevinhillinger** [comment]
logging is configured and completed out with logrus by @bobjac
